### ISSUE TITLE
VitaShell Not Detecting Free Space Properly

### ISSUE THREAD

**Issue by EricWeichhart** [TheOfficialFloW/VitaShell#237] opened 2017-05-16 13:04 UTC
I'm currently facing a problem with VitaShell as the free space is not detected properly.

The initial problems that I was facing is that the free space was ridiculously reduced and often show as used by the system. At first I though it was confusing free space with the used one, or it was just an error with CMA as I was restoring backups. I decided to make it clean, download the games and use QCMA to make backups (since it was my theory at the time) but I was still facing the same problems.

Basically the first time the hdd works flawlessly but after the second or third time (when rebooting I mean) I start to face the problems (using a 500gb Seagate hardrive with a power case).

Today it got worse, as VitaShell is showing a full drive despite of having 322 GB left and 0kb left after mounting and unmounting the drive:

After mounting the hdd:
![2017-05-16-084941](https://cloud.githubusercontent.com/assets/28657151/26107075/6fdaf862-3a1e-11e7-88c7-ba33f66eeed1.jpg)

After mounting as ux0 (as I wasn't able to take screens, here is after taking it back to uma0)
![2017-05-16-085047](https://cloud.githubusercontent.com/assets/28657151/26107122/945239f8-3a1e-11e7-9d3c-7448741bf957.jpg)

How my hard drive is seen by Windows:
![01](https://cloud.githubusercontent.com/assets/28657151/26107166/ba3699f2-3a1e-11e7-8916-f6cb792119d4.png)

I was able to copy a file and get it detected by VitaShell, however I'm not sure what to do in this situation. I'm still currently checking if I can find a solution.

**Comment by EricWeichhart** [comment] 2017-05-16 13:43
Update: if I delete stuff on the hdd via Windows, the changes are reflected on VitaShell so probably the -/- is produced when a file is added after having the drive detected as full.

Tried copying ux0 to uma0 but didn't do anything.

**Comment by jeremyj563** [comment] 2017-07-08 15:55
I **am** able to reproduce this bug.

I have a 500GB externally powered USB HDD attached to my PSTV. It has about 300GB of free space but when mounted in VitaShell it shows the drive is totally full.

The only work around I have found it to create a huge 300GB file and then delete it within VitaShell. It takes about a minute to delete the file and then the correct amount of free space is shown. Everything works perfectly until the drive is unmounted and then the process must be repeated.

You can create a file of any size instantly in Windows using fsutil as follows:

**fsutil file createnew d:\dummy.bin 319975063552**

I have not tried Enso yet so I am not sure if this bug has been already addressed in usbmc (https://github.com/yifanlu/usbmc). I am waiting for the official stable release of Enso to try it out.

**Comment by jeremyj563** [comment] 2017-07-08 15:58
Also worth mentioning: I was previously using a ~200GB HDD and this issue was non-existent so perhaps this bug is related to using a storage device that is greater than a certain size (possibly 250GB?).

I will see if I can do some more testing later to determine this potential "size limitation".

**Comment by salamcast** [comment] 2017-07-20 19:28
I saw this issue yesterday when I switched to a 500GB drive formatted as exFat.  I fixed it by reformatting the drive as fat32; but I had to do it on my Mac, win 10 doesn't seem to allow formatting drives bigger than 32GB as fat32.  The changing the file system to Fat32 should fix the problem for now, hope this helps.  I am also using a PSTV, without vita memory cards.

**Comment by jeremyj563** [comment] 2017-07-31 18:26
@salamcast 
I just tried reformatting to FAT32 using fat32format (http://www.ridgecrop.demon.co.uk/index.htm?guiformat.htm), the drive is undetectable by the Vita (as expected since I had previously tried formatting a 250GB drive with FAT32 and had the same result...)

Can anyone else confirm that they have a 500GB HDD working correctly with FAT32 filesystem?

**Comment by salamcast** [comment] 2017-07-31 22:59
Is your drive MBR or GPT?  I am using MBR and my drive is self powered.  Try using gparted with a virtualbox to reformat

**Comment by jeremyj563** [comment] 2017-08-05 17:34
@salamcast Thanks for the suggestions. I have been using MBR. I tried formatting the drive in Linux and with other Windows apps (both FAT32 and exFAT) but nothing worked. I did not try GParted but I do have a UBCD I could boot and try later just to experiment.

I began to suspect my drive was bad (or the enclosure for that matter) but after doing a full erase and scan in MHDD I decided that was not the issue either.

I ended up tracking down a Mac to try formatting it FAT32... Strangely that resolved everything. My 500GB drive appears to be working perfectly for everything (Vita games, Adrenaline, RetroArch, Homebrew etc..). It now correctly displays the free space. I have it setup to automount on boot using enso with usbmc. This setup is AMAZING!

Why in the world would it matter what device it is formatted on? And why the heck a Mac?? It's so strange, though I'm sure there is a reasonable explanation. I'm not very technical when it comes to filesystems and partitions...

**Closed** 2017-09-17 14:21 UTC
Labels: bug

**Comment by Prangalf** [comment] 2020-06-08 11:30
I saw in one Nanospeed gamer (popular youtuber) video that below 128 GB you can format using default allocation size, but for drives with more capacity you have to use 64k, i created as MBR partition, 64k allocation size, without any name on windows and worked flawlessly for my pstv with 1TB hd since then.

**Comment by deadair3210** [comment] 2020-06-08 14:44
Allocation size matters for drives bigger than 128GB for most consoles
