### ISSUE TITLE
Freeze when copy/move/delete file

### ISSUE THREAD

**Issue by BigBoot** [TheOfficialFloW/VitaShell#56] opened 2016-09-08 20:42 UTC
The latest masters seems to freeze whenever I copy/move/delete a file.
Renaming still works.

**Comment by BigBoot** [comment] 2016-09-08 20:47
Pressing circle to cancel the progress dialog will result in the operation to complete nonetheless and not  freeze.

**Comment by TheOfficialFloW** [comment] 2016-09-08 20:51
This is weird, I do not encounter this problem

**Comment by BigBoot** [comment] 2016-09-08 20:57
Only happens with really small files apparently.
The colors.txt triggers the freeze.

**Comment by BigBoot** [comment] 2016-09-08 21:00
Latest stable works without a problem.

**Comment by BigBoot** [comment] 2016-09-08 21:08
limyz can you reproduce?

**Comment by limyz** [comment] 2016-09-08 21:10
@BigBoot I haven't had time to set up Ubuntu and vitasdk. Drop me .vdk for testing if possible.

**Comment by BigBoot** [comment] 2016-09-08 21:12
[VitaShell.zip](https://github.com/TheOfficialFloW/VitaShell/files/462714/VitaShell.zip)
Rename to .vpk (Github only allows zip)

**Comment by limyz** [comment] 2016-09-08 21:22
I managed to reproduce the bug when trying to copy a small textfile from ux0:\ to ux0:\user. Do note that the time reflected in VitaShell changes accordingly. Can we revert to an earlier commit to see the problem goes away?

**Comment by BigBoot** [comment] 2016-09-08 21:37
It worked till 54d0b65 after that the bug exists.

**Comment by TheOfficialFloW** [comment] 2016-09-09 04:41
I tried every IO operation with small text files in every folder, but it didn't even freeze one time. Do you guys have any language file or theme set? Also, does it crash constantly or only sometimes?

**Comment by limyz** [comment] 2016-09-09 05:04
@TheOfficialFloW Refer to @BigBoot uploaded VitaShell or lastest master. Using a PSV1k with no language file or theme set.

**Comment by BigBoot** [comment] 2016-09-09 10:48
Dang this one is really tricky...
It seems to be a race condition causing dialog_step to stay at COPYING/MOVING/DELETING instead of going to COPIED/MOVED/DELETED.
Was looking into it but now I suddenly can't cause it to freeze anymore... 
It either happens reliably or not at all...

**Comment by limyz** [comment] 2016-09-09 16:33
Has the bug been resolved? I still see commits to the current master. I recommend having an experimental branch so that we can have master to fall back on. I may spend some time to investigate this issue if the problem persists.

**Comment by BigBoot** [comment] 2016-09-09 17:44
Tbh I kinda don't know what to do, since I can't get it to appear anymore it's hard to pinpoint where it's coming from exactly, expecially with the limited debugging features we currently have.

**Comment by limyz** [comment] 2016-09-09 17:56
Ahhh what tough luck. Since the problem disappears, we probably can get away with it until the user reports this again lol. Did your latest commit make the problem disappear?

**Comment by BigBoot** [comment] 2016-09-09 17:56
nah just some small texteditor fixes

**Comment by limyz** [comment] 2016-09-09 17:57
Cool let's close this and see v1.0 go boom boom

**Comment by TheOfficialFloW** [comment] 2016-09-09 19:19
Do you guys use hangouts? I would like to create a VitaShell group where we can discuss things :)

**Comment by limyz** [comment] 2016-09-09 19:28
limyz.sg@gmail.com
DELETING IN 10 MINS

**Comment by limyz** [comment] 2016-09-29 16:25
It's been over 21 days since the bug last occurrence. Can anyone verify if this still exists? If not, I recommend for this issue to be closed.

**Closed** 2016-09-30 03:50 UTC
Labels: bug

**Comment by xenovia242** [comment] 2016-10-07 08:16
Molecular Shell freezes after getting the prompt to update to 0.99. If I use flight mode I can only use the left thumb stick, but can't access anything. Any ideas?

**Comment by blackmodjo** [comment] 2022-05-31 14:49
Issue is still there
