### ISSUE TITLE
Incomplete FTP File Transfer

### ISSUE THREAD

**Issue by Y05H10** [TheOfficialFloW/VitaShell#29] opened 2016-09-02 12:55 UTC
Trying to Copy a larger-ish File (200MB+) often turns out Incomplete for me.
The File will be in the Directory but will not have the correct size, thus leaving me with Error 0xFFFFFFFF when trying to Install. 

The FTP Transfer Process does complete seemingly successful and takes as long as it usually would for the original file size.

-usually i try to copy it to ur0:/homebrew/vpks/ but copying it into ur0:/ shows the same behaviour.
-Rebooting / Rebuilding the Database in the Vita's Safe Mode does not help.
VitaShell 0.86
-I do have a 64GB Vita Memcard 
(since these are not usually available in Germany/EU i thought i should point that out)

**Comment by limyz** [comment] 2016-09-02 22:22
Have you tried using an alternative method (via USB transfer)? If you are in a noisy environment, I suggest you have your PS Vita stay close to your access point until the transfer is completed.

Otherwise, this will be duplicate of #13.

**Comment by TheOfficialFloW** [comment] 2016-09-03 20:54
Fixed in 0.9

**Closed by TheOfficialFloW** 2016-09-03 20:54 UTC
