### ISSUE TITLE
Building issues

### ISSUE THREAD

**Issue by cmsj** [TheOfficialFloW/VitaShell#356] opened 2018-01-09 21:10 UTC
I think the wiki page with the building instructions is missing at least one step now libarchive is being used, I did:

```
 * Download/unpack libarchive
 * cd build ; ./autogen.sh ; cd ..
 * ./configure --host=arm-vita-eabi --prefix=$VITASDK/arm-vita-eabi
 * make && make install
```

although after doing that, trying to make VitaShell I get:

```
$ make
[  1%] Building C object CMakeFiles/VitaShell.dir/main.c.obj
In file included from /Users/cmsj/hacking/scratch/VitaShell/main.c:19:0:
/Users/cmsj/hacking/scratch/VitaShell/main.h:47:10: fatal error: vitashell_user.h: No such file or directory
 #include <vitashell_user.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/VitaShell.dir/main.c.obj] Error 1
make[1]: *** [CMakeFiles/VitaShell.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by cmsj** [comment] 2018-01-09 21:45
@devnoname120 suggested on IRC that this was because the kernel/user modules aren't built automatically. I can get the kernel one to build as part of the main build process, but I'm not having much luck with the user modules yet.

**Comment by devnoname120** [comment] 2018-01-09 21:53
@cmsj I think you only need the `user` module.

Have you tried [`add_subdirectory()`](https://stackoverflow.com/questions/5628927/cmake-subdirectories-dependency)?
You'll also need to add `user.suprx` to `${res_files}`, link the library, and add the user folder to `include_directories()`.

**Comment by cmsj** [comment] 2018-01-09 22:05
@devnoname120 I think building the `user` module depends on the `kernel` one having been both built and installed (it links with `-lVitaShellKernel2_stub`), similarly building VitaShell depends on the `user` module having been both built and installed. I did `add_subdirectory()`, but that just builds the modules AFAICT, it doesn't install them, so the user module still fails. I can build/install the user/kernel modules by hand I get their include/lib files in `$VITASDK` and the VitaShell build progresses, so this may just need the wiki to also say "build/install these two things first"

**Comment by devnoname120** [comment] 2018-01-09 22:18
I will do a pull request tomorrow if you're not in a hurry.

**Comment by cmsj** [comment] 2018-01-09 22:27
@devnoname120 no hurry, just wanted to do some experiments in VitaShell's code. FWIW one other thing I noticed is warnings about implicit declarations of `sceAppMgrGameDataMount` and `sceSysmoduleUnloadModuleInternalWithArg`. At least the former of those was only added to vita-headers a few months ago and isn't present in the sdk I installed today.

**Comment by cmsj** [comment] 2018-01-11 16:26
@TheOfficialFloW could you mention how you configured/built libarchive? With manual installs of the user/kernel modules, I can get pretty close to building VitaShell, but something is going wrong with libarchive.

**Comment by cmsj** [comment] 2018-01-12 00:31
fwiw for libarchive I used `./configure CC=arm-vita-eabi-gcc --prefix=$VITASDK/arm-vita-eabi --host=arm-vita-eabi --disable-bsdtar --disable-bsdcat --disable-bsdcpio --without-xml2` but I hit a few POSIX related issues (no `memory.h`, and `archive_write_disk_posix.c` was a disaster of missing functions :)

**Comment by TheOfficialFloW** [comment] 2018-01-14 15:15
I'll share my patch to libarchive after my finals.

**Comment by devnoname120** [comment] 2018-01-14 15:16
@cmsj The dependency issues should be fixed by https://github.com/TheOfficialFloW/VitaShell/pull/357/
I haven't been able to try though since libarchive is missing.

**Comment by TheOfficialFloW** [comment] 2018-01-14 18:48
@cmsj voila: https://gist.github.com/TheOfficialFloW/cc46e7411739ef03d065ac025cd7e98c

**Comment by cmsj** [comment] 2018-01-14 23:17
@TheOfficialFloW thanks very much for that. Out of interest, did you have to do anything with libxml2? I can get libarchive and VitaShell to build only if I configure libarchive also with `--without-xml2`.

**Comment by devnoname120** [comment] 2018-01-14 23:36
@TheOfficialFloW It seems that Vitashell requires `liblzma` as well. Could you add it to vitasdk/packages? I've already added libarchive.

**Comment by cmsj** [comment] 2018-01-15 13:24
(note that `liblzma` is covered by https://github.com/vitasdk/packages/pull/45 )

**Comment by devnoname120** [comment] 2018-01-16 00:56
Fixed by https://github.com/TheOfficialFloW/VitaShell/pull/359.

**Comment by devnoname120** [comment] 2018-01-28 15:11
@TheOfficialFloW Why did you close this issue? It's not fixed as you reverted my changes (without letting me know), and once by luck I stumbled on your revert commit and asked you what the issue is, [you didn't even answer](https://github.com/TheOfficialFloW/VitaShell/commit/55c38c3fdf8b62fdaba885c4b12bf20685c8ddef#commitcomment-27095387).

I would appreciate if you treated your contributors better, otherwise don't be surprised you don't receive as many contributions as you would like to.

**Comment by TheOfficialFloW** [comment] 2018-01-28 15:22
@devnoname120 
Because as I said it' too slow and it takes around 5 seconds for me and was annoying when doing alot of compilations. I've written it as a comment to your PR that's why I didn't answer your question. Sorry about not letting you know.
And I closed this issue, because I've now written some instructions instead: https://github.com/TheOfficialFloW/VitaShell#for-developers
If you could fix the long building process, I'd be very happy to merge it again.

**Comment by quyen194** [comment] 2018-01-28 16:00
https://github.com/TheOfficialFloW/VitaShell#for-developers
@TheOfficialFloW
What did you change in the instruction?
I follow that and get compiling error.
I have to apply patch of @devnoname120 to fix that

**Comment by TheOfficialFloW** [comment] 2018-01-28 16:05
@quyen194 
What error do you get?

**Comment by quyen194** [comment] 2018-01-28 23:15
@TheOfficialFloW 
I describe here:
https://github.com/TheOfficialFloW/VitaShell/issues/365

**Comment by TheOfficialFloW** [comment] 2018-08-27 13:37
Finally fixed in https://github.com/TheOfficialFloW/VitaShell/commit/b98ce6b46c821e78d3adb296ad2348d0b416a2b8

**Closed by TheOfficialFloW** 2018-08-27 13:37 UTC
