### ISSUE TITLE
Display option

### ISSUE THREAD

**Issue by Mored1984** [TheOfficialFloW/VitaShell#78] opened 2016-09-14 14:17 UTC
- Stay live or turn off

- Make option like Vitamin v2.0 "Hold L to turn off the display" also if I didn't turn the display off it will remain on (when display switched off the data transfer be cancel {FTP client Mode}{install VPK file}).

**Comment by Dimkar3000** [comment] 2016-09-14 14:54
This feature will solve the issue I posted earlier. #75

**Comment by limyz** [comment] 2016-09-14 15:16
Duplicate of #75.

**Closed by limyz** 2016-09-14 15:16 UTC
Labels: duplicate, enhancement
