### ISSUE TITLE
VitaShell on "ur0" - "Refresh license database" freeze

### ISSUE THREAD

**Issue by OperationNT414C** [TheOfficialFloW/VitaShell#323] opened 2017-11-04 18:06 UTC
Hello,

If VitaShell is moved to "ur0" partition (using AppStorageManager for example), the feature "Refresh license database" will freeze (specially if there was not already a "license.db" file created): the refresh panel could be exited using circle button but VitaShell will still be locked.

Thank you for your help about this issue!

**Comment by duduke** [comment] 2017-11-06 19:07
I have the same problem with vita2sd mounted as ux0:
I also have a 0bytes license.db file.

**Comment by VitaSmith** [comment] 2017-11-07 14:57
I'll look into it. Right now the license database is hardcoded to use `ux0:`. Not sure about @duduke's issue though... I tested with the same conditions as the one you used (vita2sd mounted as `ux0:`) and found no issue, so there must be something else about your setup...

**Comment by VitaSmith** [comment] 2017-11-24 23:23
Man that was a tough nut to crack!

The problem has very little to do with something that's specific to VitaShell (i.e. it doesn't boil down to some hardcoded data or a typo/plain bug), as you can see the same issue with the [libsqlite](https://github.com/VitaSmith/libsqlite) sample when run from `ur0:`. So the problem is with with how Sony's default SQLite library behaves when the application that uses it does not run from `ux0:`.

After much adding of instrumentation in the SQLite calls, I can finally tell that the problem is that Sony's default VFS implementation appears to consistently return `SQLITE_IOERR_FSYNC` for `xSync()` calls that are issued against the DB journal from an application that is executed from `ux0:`. It doesn't matter that the journal is being written at the exact same location in both cases (e.g. `ux0:data\mydb.journal`), if the application that requests the synchronization does not reside on the same 'drive' as the file it is trying to synchronize, you get an error.

I suppose, we might be running afoul of some of the security measures that are embedded in Sony's SQLite library, as overriding `xSync()` with a direct call to `sceIoSyncByFd()` does not return any error, which means that the limitation in Sony's VFS is purely arbitrary.

At any rate, I should be able to have a fix for this in a few days. Then again, now that I have fixed this in [libsqlite](https://github.com/VitaSmith/libsqlite), what would be even better was if my [pull request to include libsqlite into the Vita SDK](https://github.com/vitasdk/packages/pull/36) was merged, so that I can also work on removing the sqlite code from VitaShell, and use the SDK library that includes the fix instead...

**Comment by OperationNT414C** [comment] 2017-11-25 16:21
Thank you for your research on this issue!
I had no idea it would involve a bug (or security measure) in Sony's SQLLite implementation.
I wait for VitaShell's next version with this fix!

**Comment by TheOfficialFloW** [comment] 2018-01-02 10:13
@VitaSmith Are you interested to work more actively on VitaShell?

**Comment by VitaSmith** [comment] 2018-01-18 23:09
@TheOfficialFloW, 

Sorry, I've been busy with other stuff. I have now created a pull request that should fix the issue.

**Comment by pralima87** [comment] 2018-01-19 19:06
So is there a fix for this?

**Comment by VitaSmith** [comment] 2018-01-22 00:31
Yes. As indicated above, the fix was merged. Should therefore be available in next release.

**Closed** 2018-01-25 09:18 UTC
Labels: bug
