### ISSUE TITLE
"At least 16.00 EB more space is needed."

### ISSUE THREAD

**Issue by TomTsunami** [TheOfficialFloW/VitaShell#355] opened 2018-01-09 19:07 UTC
Trying to extract a ~3GB zip file gives me this error.  Upon inspection, the file "gamedata.bin" inside the zip archive is labeled as 16.00 EB in Vitashell.  (In Windows it is 3.04 GB).

**Comment by cmsj** [comment] 2018-01-09 22:57
which version of VitaShell are you using? 1.78 added support for opening archives >2GB

**Comment by TomTsunami** [comment] 2018-01-10 17:22
I am using VitaShell 1.78.  I used Molecular Shell 1.43 to extract and had no issues - see screenshots.

![0110181212_vita](https://user-images.githubusercontent.com/15306247/34785995-bdf38f02-f600-11e7-91ba-ea3cd86008d1.jpg)
![0110181213_molecular](https://user-images.githubusercontent.com/15306247/34786004-c0f275e2-f600-11e7-9c08-7c0def9cbf30.jpg)

**Comment by TheOfficialFloW** [comment] 2018-01-10 17:24
Looks like the issue is that off_t from the stat struct is used which is only 32bit wide. I'll fix this bug soon.

**Comment by TheOfficialFloW** [comment] 2018-01-25 09:18
Fixed in https://github.com/TheOfficialFloW/VitaShell/commit/6c2c40caab05e244f0c8633e0b15df6e489bf1f8

**Closed by TheOfficialFloW** 2018-01-25 09:18 UTC
