### ISSUE TITLE
Side effects using FTP transfer when reaching full size of Vita TV internal memory.

### ISSUE THREAD

**Issue by benclaff** [TheOfficialFloW/VitaShell#62] opened 2016-09-11 15:31 UTC
I transferred many files to my vita TV through the FTP functionnality of vitashell 0.95.
The transfer went fine, and Filezilla reported a correct transfer of the files.

Then going back to the vita TV and  vitashell, I realized that all the last files had a size of 0 bytes. This is normal as I transfered more files than the internal memory could handle.
I reached the full size of the internal memory, confirmed by the systeme messages "You have less than <40 Mb "

Side effects observed:

- Filezilla reported a successful transfer while the transfer was in fact failing. The ftp server on the vita side should report errors when maximum memory capacity is reached.

- I deleted all the 0 bytes files, but the vita TV still reports the internal memory card as full ! And i cannot launch any software or copy any files because of this). I get this exact message in the vita TV menu, even after reboot (the bublle menu): "Free space on the memory card is less than 40mb".

- I observed that the "content manager" reports these extra data as "Other" (gray color).

- Rebooting the vita TV and using the offline henkaku do not work anymore (needs storage as cache?), exiting the mail application after this attemps brings an unstable bubble menu, with flickering screen. After this bug, impossible to restart vita TV via "shutdown" option, only solution is to cut the power.

- Deleting the directories in which the failes transfers occured didn't change anything. I think there is an issue in the ways used blocks are registered. Vita memory formating the only option ?

**Comment by limyz** [comment] 2016-09-11 21:39
You cited multiple problems in a single issue.

> Filezilla reported a successful transfer while the transfer was in fact failing. The ftp server on the vita side should report errors when maximum memory capacity is reached.

According to the RFC 959, there is no provision for detecting bits lost or scrambled in data transfer; this level of error control is handled by the TCP. This is compliant with the specifications. Not an issue with VitaShell but with https://github.com/xerpi/libftpvita.

> I deleted all the 0 bytes files, but the vita TV still reports the internal memory card as full ! And i cannot launch any software or copy any files because of this). I get this exact message in the vita TV menu, even after reboot (the bublle menu): "Free space on the memory card is less than 40mb".

I thought it might be obvious, deleting 0 byte files does not free up memory in your memory card. You need to delete files that occupy space.

> I observed that the "content manager" reports these extra data as "Other" (gray color).

This works as intended and does not affect the user in any way.

> Rebooting the vita TV and using the offline henkaku do not work anymore (needs storage as cache?), exiting the mail application after this attemps brings an unstable bubble menu, with flickering screen. After this bug, impossible to restart vita TV via "shutdown" option, only solution is to cut the power.

This is a problem with Henkaku. Refer to https://github.com/henkaku/offline-installer/releases.

> Deleting the directories in which the failes transfers occured didn't change anything. I think there is an issue in the ways used blocks are registered. Vita memory formating the only option ?

You need to delete files which are actually taking up space on the memory card. You can check how much space is remaining by pressing the START button in VitaShell.

As these raised issues are not related or critically affecting the functionality of VitaShell, I will close this issue.

**Closed by limyz** 2016-09-11 21:39 UTC
Labels: invalid
